name: large-artifacts

on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15]
    name: artifact upload on ${{ matrix.os }}
    steps:
        - shell: bash
          run: |
            mkdir artifact-path
            head -c 357914624 /dev/urandom > artifact-path/random_bytes_1
            head -c 357914624 /dev/urandom > artifact-path/random_bytes_2
            head -c 357914624 /dev/urandom > artifact-path/random_bytes_3
        - uses: actions/upload-artifact@v4
          with:
            name: my-artifact-${{ matrix.os }}
            path: artifact-path/*
            retention-days: 1
          env:
            ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY: 5
