name: large-artifacts

on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    name: artifact upload on ${{ matrix.os }}
    steps:
        - shell: bash
          run: |
            brew install pv
            brew install pigz
            
        - shell: bash
          run: |
            mkdir artifact-path
            head -c 1073743872 /dev/urandom > artifact-path/random_bytes
      
        - uses: paveliak/zupload-artifact@main
          name: Upload with concurrency of 1
          with:
             name: my-artifact-${{ matrix.os }}-concurrency_1
             path: artifact-path/random_bytes
             concurrency: 1 

        - uses: paveliak/zupload-artifact@main
          name: Upload with concurrency of 5
          with:
            name: my-artifact-${{ matrix.os }}-concurrency_5
            path: artifact-path/random_bytes
            concurrency: 5 

        # - uses: actions/upload-artifact@v4
        #   name: Upload with default concurrency
        #   with:
        #     name: my-artifact-${{ matrix.os }}-default_concurrency
        #     path: artifact-path/*
        #     retention-days: 1
